services:
  postgres:
    container_name: postgres-sql
    image: postgres    
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres: /var/lib/postgres/data
    networks:
      - spring-boot-network

  spring-boot-app:
    container_name: spring-demo
    image: spring-demo
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  spring-boot-network:
    driver: bridge

# docker-compose up - start the containers.
# docker-compose -d up
# docker-compose down - stop the containers.